#pragma once

#include "NativeGameplayTags.h"

namespace InventoryOperationTags
{
	// 固定原生 Tag 让调用方能够稳定地分支处理失败原因，避免比较本地化文本或字符串。
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InvalidItem);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InvalidQuantity);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InvalidHandle);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ForeignHandle);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IncompatibleItem);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InsufficientQuantity);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoCapacity);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Overflow);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StalePlan);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MissingStrategy);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnsupportedOperation);
	PACKSYSTEMPLUGIN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoChange);
}
